# general
root: results/qm9
run_name: mu
experiment_description: "Mu - 100k train samples. 19.4k valid samples."

seed: 1
dataset_seed: 1
append: true
default_dtype: float32

# --- M O D E L --- #
model_builders:
  - HeadlessNodeModel
  - Heads
  - cls: NodewiseReduce
    name: node_pooling
    field: node_mu
    out_field: mu
  - cls: Norm
    name: vector_norm
    field: mu

# - general - #
use_weight_norm: false # Cannot jit compile when using this
strict_irreps: false
scalar_attnt: false
use_attention: true
head_dim: 32
latent_zero_init_last_layer_weights: true
readout_latent_zero_init_last_layer_weights: true

# - cutoffs - #
r_max: 5.0

# - radial basis - #
edge_radial_attrs_basis: geqtrain.nn.BesselBasisVec
TanhCutoff_n: 6
num_basis: 8

# - symmetry - #
# l_max: 2
irreps_edge_sh: 1x0e+1x1o+1x3o+1x5o
parity: o3_full

# --- interaction layers --- #
num_layers: 2
latent_dim: 64
env_embed_multiplicity: 16

latent: geqtrain.nn.ScalarMLPFunction
mlp_latent_dimensions: [128]
mlp_nonlinearity: swiglu

# --- START HEADS --- #
head_wds: 0.0
head_node_output_wd: false
heads:
  head_mu:
    field: node_features
    out_field: node_mu
    out_irreps: 1x1o
    model: geqtrain.nn.ReadoutModuleWithConditioning
    conditioning_field: node_attrs
# ---  END HEADS  --- #

# --- E N D   M O D E L --- #

# --- D A T A S E T --- #

dataset_num_workers: 1

# - train - #
dataset_list: # if you provide only training dataset, it will be split 80-20% in train and validation
  - dataset: npz
    dataset_input: /scratch/angiod/qm9/debug/
    key_mapping:
      pos: pos # the blue keywords are the kwords present in the npz, they are mapped to the red kwords that are present/used in code
      atom_type: node_types
      edge_index: edge_index
      edge_type: edge_type
      aromatic: aromatic
      hybridization: hybridization
      num_hs: num_hs
      mu: mu
      eq_attrs: eq_attrs

# train_idcs: /scratch/angiod/qm9/mu.debug.txt

# validation_dataset_list: # If you also provide the validation, this will be used as validation and the full training as training
#   - validation_dataset: npz
#     validation_dataset_input: /my_path/to/qm9/processed_valid
#     key_mapping:
#       pos: pos
#       x: node_input_features
#       y: graph_output
#       z: node_types

# - register fields - #
node_fields:
  - node_types
  - aromatic
  - hybridization
  - num_hs
  - node_mu
  # - eq_attrs

edge_fields:
  - edge_type

graph_fields:
  - mu

# - define node attributes - #
node_attributes:
  node_types: # this kword must match the red kword in key_mapping
    embedding_dimensionality: 8
    fixed: true
  aromatic:
    embedding_dimensionality: 8
    num_types: 2
    fixed: true
  hybridization:
    embedding_dimensionality: 8
    num_types: 4
    fixed: true
  num_hs:
    embedding_dimensionality: 8
    num_types: 8
    fixed: true

# eq_node_attributes:
#   eq_attrs:
#     embedding_dimensionality: 3
#     irreps: 1x1o

edge_attributes:
  edge_type:
    embedding_dimensionality: 8
    num_types: 4
  

type_names:
  - X
  - H
  - He
  - Li
  - Be
  - B
  - C
  - N
  - O
  - F

target_names: ['mu']
target_key: mu

# --- R E G U L A R I Z A T I O N --- #

# dropout: 0.001
# dropout_edges: 0.001

# --- L O S S --- #

loss_coeffs:
  - mu: # target -? key taken from dat dict of batch
    - 1. # scalar that can be used to weight/rescale impact of this loss onto gradients
    - MSELoss # loss function

# --- M E T R I C S --- #

metrics_components:
  - mu:
    - L1Loss

# --- L O G G I N G --- #

verbose: info
log_batch_freq: 50

wandb: false
wandb_project: qm9
# code_folder_name: qm9 # - use if you run geqtrain from a different repo, to save source code of your repo - #
wandb_watch: true # - log gradients and/or parameters of the model - #
wandb_watch_kwargs:
  log: 'all'      # either 'gradients', 'parameters', 'all' or None
  log_freq: 1000  # log every N batches
  log_graph: true # log graph topology

# --- T R A I N I N G --- #

batch_size: 32
validation_batch_size: 32
dataloader_num_workers: 1

# Configure maximum batch sizes to avoid GPU memory errors. These parameters have to be configured according to your GPU RAM #
skip_chunking: true
batch_max_atoms: 10000             # Limit the maximum number of nodes of a graph to be loaded on memory in a single batch

max_epochs: 150
learning_rate: 1.e-4
train_val_split: random
shuffle: true
metrics_key: validation_loss

# - optimizer - #
optimizer_name: AdamW
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.1
# max_gradient_norm: 10.

lr_scheduler_name: CosineAnnealingLR
lr_scheduler_eta_min: 1.e-8

# # lr scheduler, drop lr if no improvement for tot epochs
# lr_scheduler_name: ReduceLROnPlateau
# lr_scheduler_patience: 3
# lr_scheduler_factor: 0.7

early_stopping_lower_bounds:
  LR: 1.0e-10

early_stopping_patiences:
  validation_loss: 50

sanitize_gradients:   false # If true, zero out NaN gradients. Activate only if you are training on a dataset which can have bad behaving graphs
model_requires_grads: false # If true, run validation step without using torch.no_grads(). Use if your model uses automatic differentiation internally